name: color
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.4.5.1=hecc5488_0
  - cairo=1.14.12=h80bd089_1005
  - certifi=2020.4.5.1=py36h9f0ad1d_0
  - cudatoolkit=10.0.130=0
  - ffmpeg=4.0.2=ha0c5888_2
  - fontconfig=2.13.1=he4413a7_1000
  - freeglut=3.0.0=hf484d3e_1005
  - freetype=2.10.1=he06d7ca_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.56.2=had28632_1001
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.5.19=h2a4e5f8_1
  - graphite2=1.3.13=he1b5a44_1001
  - harfbuzz=1.9.0=he243708_1001
  - hdf5=1.10.2=hc401514_3
  - icu=58.2=hf484d3e_1000
  - jasper=2.0.14=habb8e15_1
  - jpeg=9c=h14c3975_1001
  - ld_impl_linux-64=2.34=h53a641e_0
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libglu=9.0.0=he1b5a44_1001
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=16_openblas
  - libopenblas=0.3.9=h5ec1e0e_0
  - libopencv=3.4.2=hb342d67_1
  - libpng=1.6.37=hed695b0_1
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_2
  - llvm-openmp=10.0.0=hc9558a2_0
  - lz4-c=1.9.2=he1b5a44_0
  - ncurses=6.1=hf484d3e_1002
  - nettle=3.3=0
  - numpy=1.18.1=py36h7314795_1
  - olefile=0.46=py_0
  - opencv=3.4.2=py36h6fd60c2_1
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1f=h516909a_0
  - pcre=8.44=he1b5a44_0
  - pillow=6.2.1=py36hd70f55b_1
  - pip=20.0.2=py_2
  - pixman=0.34.0=h14c3975_1003
  - psutil=5.7.0=py36h8c4c3a4_1
  - pthread-stubs=0.4=h14c3975_1001
  - py-opencv=3.4.2=py36hb342d67_1
  - python=3.6.9=h9d8adfe_0_cpython
  - python_abi=3.6=1_cp36m
  - pyyaml=5.3.1=py36h8c4c3a4_0
  - readline=8.0=hf8c457e_0
  - setuptools=46.1.3=py36h9f0ad1d_0
  - sqlite=3.30.1=hcee41ef_0
  - tk=8.6.10=hed695b0_0
  - wheel=0.34.2=py_1
  - x264=1!152.20180806=h14c3975_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_0
  - yaml=0.2.3=h516909a_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h6597ccf_3
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - cachetools==4.1.0
    - chardet==3.0.4
    - cycler==0.10.0
    - gast==0.2.2
    - google-auth==1.14.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.28.1
    - h5py==2.10.0
    - idna==2.9
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.2.0
    - markdown==3.2.1
    - matplotlib==3.2.1
    - oauthlib==3.1.0
    - opt-einsum==3.2.1
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - pypng==0.0.20
    - python-dateutil==2.8.1
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scipy==1.1.0
    - six==1.14.0
    - tensorboard==2.0.2
    - tensorflow-estimator==2.0.1
    - tensorflow-gpu==2.0.0
    - termcolor==1.1.0
    - urllib3==1.25.9
    - werkzeug==1.0.1
    - wrapt==1.12.1
prefix: /opt/conda/envs/color

